name = "vs-shorts-automation"
main = "src/index.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "vs-automation-db"
database_id = "d6d19bc4-96c1-4055-875d-46809c1a82c3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "vs-shorts-bucket"

[triggers]
crons = ["* * * * *"] # 매분 작동 (DB 설정 시간과 비교하여 실제 실행)
